import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useRouter } from 'next/router'

const thankyou = ()=>{
    const router = useRouter();
    const data = router.query;
    return(
    <div className={styles.container}>
      <Head>
        <title>Thank you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3 className={styles.title}>
          Thank you for using <a href="/">Eco-Commute!</a>
        </h3>
        <h3>{`Your ticket will be sent to ${data.email}`}</h3>
        <p>You can close the app here or click on eco commute to book another ticket.</p>
        </main>
    </div>
    )
}

export default thankyou